In [1]:
# Question1:

In [2]:
import numpy as np
a=np.random.random((10,1))
print(a)
print(a.mean())



[[0.89253588]
 [0.73885127]
 [0.46470312]
 [0.09444225]
 [0.90044797]
 [0.98684124]
 [0.52172589]
 [0.00982255]
 [0.32268579]
 [0.39144807]]
0.532350403067082


In [3]:
# Question2

In [4]:
a=np.random.random((20,1))
print(a)
print(a.std())
print(a.var())

[[0.80807459]
 [0.7247799 ]
 [0.4028248 ]
 [0.19760351]
 [0.35451863]
 [0.42484859]
 [0.85314011]
 [0.35680609]
 [0.14907666]
 [0.10890649]
 [0.97643352]
 [0.2553596 ]
 [0.66242674]
 [0.73025922]
 [0.40818588]
 [0.20071172]
 [0.4071971 ]
 [0.91798631]
 [0.96708895]
 [0.7542503 ]]
0.2831095603018519
0.08015102313430791


In [5]:
#Question3

In [13]:
a=np.random.random((10,20))
b=np.random.random((20,25))
print(np.matmul(a,b))



[[4.85388278 4.06334895 4.93866795 5.68675344 4.20564948 4.88769217
  4.81262075 4.0210904  4.32190654 3.82779352 4.5510376  3.1707977
  4.6619774  4.6600366  3.48231148 5.65932527 4.32015301 3.8796131
  4.84133495 4.65620548 4.61937407 4.21002695 5.38024872 5.26961021
  5.27458534]
 [4.01809381 3.43172019 3.85985054 4.49112658 3.37142736 4.05107692
  4.63049477 3.46416848 3.61185167 3.66910842 3.61092177 3.127748
  4.44951251 4.15650275 3.09512988 3.70845215 3.55581809 4.14944241
  3.37077132 4.50802147 3.10990576 4.01476937 4.49009792 3.53637191
  3.83331288]
 [5.44925589 5.17990565 6.47995328 6.45570017 5.79855732 5.6121012
  5.81644609 5.47659213 6.20447822 5.49965799 6.2038227  4.54413535
  5.42329378 5.40336281 3.84926098 6.81715165 5.68946102 5.21577931
  5.67822019 6.09215286 4.92865881 5.36202733 6.40015706 6.42921408
  5.65066844]
 [5.52556501 5.16661473 6.01708856 5.48229526 5.09179504 5.6200133
  5.40030289 4.47684117 5.52740504 4.88579238 6.50032656 4.22709804
  5.76249123

In [11]:
# Question4

In [15]:
def fun(j):
    return(1/1+np.exp(-j))
B=[]
A=np.random.random((10,1))
for j in A:
    ans=fun(j)
    B.append(ans)
print(np.array(B))

[[1.72668627]
 [1.46764503]
 [1.59534874]
 [1.66477103]
 [1.554477  ]
 [1.64947151]
 [1.53009804]
 [1.49536353]
 [1.51261577]
 [1.89606837]]
